- README.md
- lib/mviewer.js
This allow to auto-configure WMTS layer from getCapabilities if "fromcapacity" is set to true.
It use the OpenLayers 3 classes : 
- ol.format.WMTSCapabilities : to parse getCapabilities XML to an object
- ol.source.WMTS.optionsFromCapabilities() : to generate WMTS config from the getCapabilities object and config.xml parameters
> Add fromcapacity implementation based on OL3

- README.md
- lib/mviewer.js
This fix has only been tested on a geojson layer and a custom layer loading a geojson file.
The process of the searchable property of the layer has moved just after _map.addLayer allowing access to the features of layer. I hope this don't break the process of layers indexed with Elasticsearch.
> Load layer indexed with Fuse only once (fix #59)

- README.md
- lib/mviewer.js
This pull request adds support for GetFeatureInfo from ArcGIS Server WMS services.
It adds two possible infoformats which are specific to ArcGIS Server: "application/vnd.esri.wms_raw_xml" and "application/vnd.esri.wms_featureinfo_xml".
These formats are XML not GML.
Therefore I replaced in the original source code "gml" by "xml" in order to be more generic.
Since I haven't found any ArcGIS server with CORS activated, I used a local proxy for retrieving the GetFeatureInfo responses.
I updated the readme file.
> Add support for GetFeatureInfo from ArcGIS Server WMS services

- README.md
- js/mviewer.js
L'idée est de corrigé le souci rencontré avec MapProxy dans le ticket suivant :
https://github.com/geobretagne/mviewer/issues/94
Mon commit est pas super lisible.
J'ai essentiellement introduit ces lignes de code dans mviewer.js pour les couches WMS :
var params = {
'LAYERS': baselayer.layers,
'VERSION': '1.1.1',
'FORMAT': baselayer.format,
'TRANSPARENT': false
};
if (baselayer.tiled !== "false") {
params.TILED = true;
}
Les applis actuelles vont continuer de fonctionner comme avant.
Cela permet simplement de passer ne mode WMS-C ou pas sans pour autant modifier le fait que les couches WMS sont tuilées.
C'est toujours une couche de type ol.layer.Tile qui est créée.
Le reste c'est essentiellement de l'indentation que j'ai corrigé.
J'ai mis à jour le readme en conséquence.
> Add optional 'tiled' param for WMS base layers

- README.md
- demo/ban.xml
- demo/fuse.xml
- js/info.js
- js/mviewer.js
- js/search.js
Création de deux nouveaux paramètres associés à la configuration searchparameters
- `querymaponclick` : pour interroger la carte après avoir sélectionné un des résultats de recherche
- `closeafterclick`: pour fermer la liste des résultats de recherche après avoir cliqué sur un élément.
Fix #158
> Nouveaux comportements associés au clic sur résultat de recherche

- js/measure.js
Traitement du ticket suivant : #67.
En passant, j'ai également modifié le texte affiché dans l'infobulle quand on a juste 1 ou 2 points dans le polygone : l'infobulle hésitait entre afficher 0 et 0m2. J'ai forcé à afficher 0 lorsque la surface est inférieure à 0.0001.
> Fix measure area tooltip

- js/search.js
Ajout d'un test sur la géométrie des objets à indexer :
- évite que le code plante
- indique dans la console les objets en erreur
cf. #185.
> Fix fuse index 185

- README.md
- demo/owsoptions.xml
- index.html
- js/configuration.js
- js/mviewer.js
- js/ogcutils.js
Pull request répondant au besoin du ticket #94.
Au passage, j'ai créé un fichier ogcutils.js pour factoriser certaines manipulations courantes avec les services OGC. J'en ai profité pour revoir la fonction _getlegendurl qui me paraissait bancale.
J'ai créé un exemple dans le répertoire demo (owsoptions.xml) dans lequel j'utilise le paramètre owsoptions pour une baselayer et pour 2 couches thématiques. C'est une variation du fichier geobretagne.xml.
J'ai mis à jour également le fichier README en conséquence.
> feat config: introduce owsoptions

- js/configuration.js
J'ai modifié et factorisé un peu le code qui était en cause dans #199.
Sans authentification avec basic auth, le chargement des images WMS passe par le fonctionnement par défaut que nous avions auparavant.
Par contre, j'ai l'impression que la partie du code qui passe par xmlhttprequest (ajout de basic auth) est plus facilement bloqué par CORS que le comportement par défaut. J'ai donc le sentiment que la partie du code qui passe par xmlhttprequest peut encore être amélioré.
> Correction issue #199

- index.html
- js/mviewer.js
Fix for #177 issue.
Share a permalink with a map opened with a fragment in the url (#config) now works correctly.
> Fix permalink creation when the current URL contains a fragment

- js/mviewer.js
#229
Le problème venait de l'utilisation de la fonction splice qui insère un élement à une position x tout en décalant l'élément (qui est à cette position  x) à la position x+1. Donc enlever 1 à x positionnait au bout d'un moment l'élément à la position 0 ce qui décalait le fond de carte à la position 1 .
#219 
J'ai supprimé la partie où l'on dessine le texte dans le canvas puis j'ai ajouté un texte au style de chaque élement de la légende ce qui me permet de dessiner une seule entité (geometry) au lieu de deux (geometry + texte).
> Fix Affichage des couches réordonnées #229 + Fix légende vectorielle #219

- README.md
- js/mviewer.js
Fix #216.
Permet d'afficher la le panneau de légende avec un panneau de couches en mode "mini".
Fonctionnement testé sans le paramètre "legendmini" pour rester compatible avec des versions antécédente.
Evolution financée par l'[ARS](https://www.iledefrance.ars.sante.fr/) Île-de-France et du [GCS-SESAN](http://www.sesan.fr/).
> legendmini param

- .github/workflows/docker-build.yaml
Only run the CI when push on master (which updates the "latest" tagged image), or when a release is made.
See #320
Tests: Untested ! I used the github web-based Actions editor, it should be valid though.
> Change gh action build strategy (#320)

- Dockerfile
alpine version is sufficient.
Image size drops from 92 to 51 Mb
BTW, I'm not convinced we need to stick to a version number
> Use nginx alpine version for docker image

- js/custom.js
Fix #367 
This PR is compliant with old version ( => load only one CSS from simple path as String).
> Allow many CSS files import

- customlayers/cluster.js
- customlayers/inventaire.js
- demo/cad/layer.js
- demo/lycee_resultat_bac.mst
- docs/doc_tech/config_layers.rst
- docs/doc_tech/config_tpl.rst
- index.html
- js/configuration.js
- js/featurestyles.js
- js/info.js
- js/mviewer.js
- js/templates.js
- templates/cadastre.parcel.mst
- templates/demo.sirene.mst
- templates/global.aeroport.mst
- templates/global.arret_ferroviaire.mst
- templates/global.gare_maritime.mst
- templates/global.lycee.mst
- templates/global.port.mst
- templates/global.reserve_naturelle_reg.mst
- templates/inventaire.mst
- templates/transport.ligne_ferroviaire.mst
This PR replaces the pin/marker for the info tool by highlighting the selected feature (if a geometry can be found) and is meant to resolve #315 . The pin is kept as a fallback for WMS GetFeatureInfo responses in HTML and GML without geometry.
The highlighting is done on a new source/layer to stay independent of hovering (but finally might be moved to the same).
Another source/layer pair was added to allow a sub selection of the feature currently visible in the info panel. To allow synchronizing actions of the carousel and the map a `feature_id` needed to be injected to the DOM which affected templating (see the doc). The internal `ol_uid` was used for this matter, as not all layers include a feature id as a property.
The PR was tested against:
* WMS layers (Geoserver, Mapserver):
* …
> Highlights features with geometry for info tool

- .github/ISSUE_TEMPLATE/autre-demande.md
- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/evolution.md
Lorsqu'on crée une issue, on part d'une page blanche et cela peut être déstabilisant si on en a pas l'habitude.
A la lecture c'est en plus parfois compliquer de comprendre le message de l'issue.
GitHub propose des templates pour remédier à ce soucis.
Je propose donc 3 template d'issue qui peuvent nous servir :
* Bug
* Evolution
* Autre demande (question, support technique, sujet de stage, autre...)
> Github template issues

- docs/doc_tech/config_app.rst
- index.html
Add new favicon parameter in application config. See #449.
If parameter is not set, default mviewer favicon is used. Example : `favicon="https://www.bretagne.bzh/app/themes/bretagne/dist/img/icons/favicon"`
> Add favicon parameter in application. Linked to #449

- js/configuration.js
- js/info.js
- js/mviewer.js
Création d'un nouveau paramètre de couche : **showintoc**
Par défaut ce paramètre a la valeur **true**. Pour désactiver l'affichage d'une couche dans la légende et l'arborescence des thématiques, il faut attribuer la valeur **false** à ce paramètre.
Cette fonctionnalité est utile pour afficher une couche de type masque ou bien encore une couche en surimpression des couches de fond. Lien avec #209
> Affichage d'une couche sur la carte mais pas dans la légende.

- js/info.js
- js/mviewer.js
Liée à #459.
* Nettoyage du code (console log, indentations)
* Nouvelle fonction pour ordonner les couches des templates selon l'ordre de visibilité des couches sur la carte (zIndex)
> Afficher les template par ordre d'affichage des couches sur la carte

- customcontrols/inventaire.js
- docs/doc_tech/config_intro.rst
- js/mviewer.js
In mviewer, permalink is constructed from public API object.
With this small adaptation, all API properties beginning with c_ like c_mycustomlayer are used in permalink.
This is the core implementation.
Then in each customlayer or component, user will have to add two methods to get and set this custom param.
Example to get value
if (API[`c_${_idlayer}`]) {
_defaultValue = API[`c_${_idlayer}`];
}
Example to set value
API[c_${_idlayer}] = 'test1,test2';
See #492
> Add capability to store small custom config in permalink

- demo/index.html
- demo/jsonfields.mst
- demo/jsonfields.xml
- docs/doc_tech/config_layers.rst
- docs/doc_tech/config_tpl.rst
- js/configuration.js
- js/info.js
This is neccessary to iterate over list items in Mustache templates
Demo in demo/jsonlayers.xml
- First create a field named **mylist** in your data with **String** value like 
```
"[
{"name": "SRFC", "league": 1},
{"name": "FCNA", "league": 2}
]"
```
- Then in config.xml, add this parameter in the layer configuration `jsonfields="mylist"`
- Finally, update your template with this section
```
<table style="width:100%;">
<thead>
<tr>
<th>CLUB</th>
<th>LIGUE</th>
</tr>
</thead>
<tbody>
{{#mylist}}
<tr>
<td>{{name}}</td>
<td>{{league}}</td>
</tr>
{{/mylist}}
</tbody>
</table> 
```
> Add new layer parameter jsonfields. 

- .github/ISSUE_TEMPLATE/evolution.md
- docs/doc_tech/config_app.rst
- index.html
- js/configuration.js
#512
* Pour le titre
Nouveau paramètre documenté afin d'ajouter un HTML simple comme titre. Si non renseigné, le paramètre natif `title` est utilisé.
Utilisation d'un `append` à la place d'un `.text()`
Cela permet également d'avoir un texte vide dans le titre (impossible actuellement) via une div avec un texte transparent.
* Pour le loader
Utilisation d'un `append` à la place d'un `.text()`
* Template issue type Enhancement
Suppression d'un doublon dans le template de demande d'évolution
* Doc
Nouveau paramètre `titlehtml` pour la section [configuration de l'application](https://mviewerdoc.readthedocs.io/fr/latest/doc_tech/config_app.html?highlight=title%3D)
**1. Définir et encoder son HTML ([site d'encodage HTML](https://www.convertstring.com/fr/EncodeDecode/HtmlEncode))**
```
<span …
```
> Titre en HTML ou classique

- js/mviewer.js
Force l'utilisation du type `Number` pour la valeur du paramètre `opacity` d'une baselayer.
https://openlayers.org/en/latest/apidoc/module-ol_layer_Base-BaseLayer.html#setOpacity
> #547 baselayer et type de valeur d'opacité

- customlayers/cluster.js
- js/info.js
#397 
Cette PR contient :
- Update du custom layer pour utiliser une classz CustomLayer
- Affiche la surbrillance pour la feature du cluster en style principal et non comme une sélection secondaire
- Ne pas changer de géométrie au clic sur un chevron (slide) car on a qu'une géométrie sur la carte (=>le cluster)
> #397 - Update cluster customlayer and fix cluster highlight

- docs/doc_tech/config_app.rst
- index.html
- js/mviewer.js
- js/zoom.js
Liée à #567 et #566.
Cette PR permet de : 
- ajouter les boutons zoom + et - ou de les masquer
- ajouter le bouton de zoom sur l'étendue initiale ou de le masquer
**Paramètres :**
- initialextenttool `<bool>` true par défaut si absent du config.xml
- zoomtools `<bool>` true par défaut si absent du config.xml
**Exemple :**
`<application initialextenttool="true" zoomtools="true"`
> #567 toolbar et boutons de zoom paramétrables

- css/mviewer.css
- index.html
- js/info.js
- js/templates.js
**Corrige l'issue #594**
Cette PR permet d'utiliser un un overlay Openlayers pour la tooltip WFS et de ne plus utiliser les pixels mais les coordonnées de la carte pour positionner la popup.
https://openlayers.org/en/latest/apidoc/module-ol_Overlay-Overlay.html
https://openlayers.org/en/latest/examples/overlay.html
La configuration mviewer et le fonctionnement avec le config.xml restent inchangés.
> #594 - Utilise un overlay ol avec coordonnées

- js/mviewer.js
Ref. #603 
Cet event `map-ready` map-ready permet à différents `listeners `(e.g extensions) de savoir quand la carte sera disponible.
Modification impactante : aucune.
> #603 - Ajout de map-ready event - mineur

- docs/doc_tech/config_app.rst
- js/info.js
Code pour l'issue #644 qui permet d'ordonner les couches des panneaux d'information selon l'ordre de la toc au lieu de l'ordre des couches de la map
> tri fiches infos selon la toc

- apps/default.xml
- demo/ban.xml
- demo/cadastre.xml
- demo/cluster.xml
- demo/cql.xml
- demo/exclusivelayer.xml
- demo/fonds.xml
- demo/geobretagne.xml
- demo/include.xml
- demo/isochroneAddon.xml
- demo/lang.xml
- demo/owsoptions.xml
- demo/selectionstyles.xml
- demo/sirene.xml
- demo/sld.xml
- demo/time.xml
- demo/v3.5.xml
- demo/v3.6.xml
Mise au format JPEG (au lieu de PNG) des orthos de GéoBretagne utilisées dans les démos.
> ortho geobretagne jpeg

- .prettierignore
- .prettierrc
- .vscode/settings.json
- docs/doc_contrib/contrib.rst
- package-lock.json
- package.json
> Lié à l'issue https://github.com/geobretagne/mviewer/issues/179
Cette PR permet de formater les fichier avec VSCode à la sauvegarde d'un fichier et ainsi éviter d'avoir des contributions avec des problèmes de style.
Les templates ont été modifiés pour utiliser la syntaxe [template string](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).
La commande suivante permet de formater automatiquement tout le répertoire `mviewer/js`  (les autres fichiers JavaScript sont à formater à la main) : 
`npm run pretty`
... issue de :
```
"scripts": {
"start": "live-server --port=5051",
"pretty": "prettier --write \"./js/**/*.{js,jsx,json}\""
},
```
Les règles définies dans le fichier [.prettierc](url) sont issues de la [doc …
> Utilisation de Prettier - format seulement

- docs/doc_tech/config_app.rst
- docs/doc_tech/config_layers.rst
Dans le cadre de l'[évolution du mviewerstudio](https://github.com/mviewer/mviewerstudio/issues/157) et notamment de l'ajout de nouveaux paramètres, la documentation du mviewer a été mise à jour avec l'ajout du badge `studio` aux paramètres suivants : 
- **Paramètres de l'application** : `Zoomtools, Initialextenttool, Titlehelp, Iconhelp, Geoloc, Mouseposition, Studio, Home, Favicon`
- **Paramètres d'une couche** : `Index, Styletitle, dynamiclegend, exclusive, toplayer, showintoc`
> Mise à jour de la documentation - Nouveaux paramètres compatibles avec le studio

- js/mviewer.js
Le paramètre styleTitle n'est pas pris en compte si on ne renseigne pas les paramètres attributeX : 
```
attributefilter 
attributevalues
attributefield 
```
Cette PR corrige ce comportement et permet de prendre en compte le paramètre `styleTitle` sans renseigner ses champs.
> Correction du bug #737 lié à l'utilisation du paramètre styletitle

- docs/doc_tech/config_app.rst
- js/configuration.js
Auparavant, quand on renseignait un icône font awesome pour le paramètre icon help, il ajoutait automatique "fa fa-" devant l'icône déclaré engendrant certains problèmes : 
- Les icônes avec le préfixe **fab** sont non reconnus : `class="fa fa-fab fa-apple"`
- Les icônes avec le préfixe **fas** sont reconnus mais mal renseignés : `class="fa fa-fas fa-asterisk"`
Ce problème est corrigé en supprimant le préfixe "fa fa-" automatiquement ajouté. 
**Attention, cette modification peut engendrer des régressions et notamment pour les fichiers de configuration où seul le nom de l'icône est déclaré.** 
Exemple : 
`iconhelp="home" `
doit être ajusté en 
`iconhelp="fas fa-home"`
ET ajustement de la documentation pour ce paramètre
> Correction de la syntaxe font awesome pour le paramètre icon help #740

- demo/external.xml
- docs/doc_tech/config_topics.rst
- js/configuration.js
**Paramétrages possibles**
- `name` : Nom de la thématique en remplacement du titre d'origine de la thématique
- `layersvisibility `: Affichage des couches composant la thématique ("all" / "none" / "default")
Démo avec demo/external.xml
Exemple de configuration 
```xml
<theme id="education"
url="https://kartenn.region-bretagne.fr/territoires/apps/default.xml"
name="Renommage Education et formation"
layersvisibility="all">
</theme>
```
> Paramétrage de thèmes externes #616

- demo/addons/filter/config.json
- demo/addons/filter/js/filter.js
- demo/filter/filter.xml
Type : Correctif issue #757 
Auparavant, le comportement était que le plugin se rechargeait toutes les 3000 ms si la feature n'a aucune donnée. La couche n'étant pas chargée, les données n'était jamais disponible jusqu'à ce qu'elle soit rendu visible.
Cette PR permet donc de recharger les données lorsqu'une couche qui doit être filtrée, n'est pas chargée (au sens visible) à l'ouverture de la carte.
Le clic sur la couche pour la rendre visible va alors intégrer les données dans le plugin filtre pour afficher les filtres attributaires correspondants et recharger le panel du plugin.
> #757 Correction du plugin filtre avec des couches non visibles par défaut

- docs/doc_tech/config_app.rst
- js/configuration.js
- js/info.js
Issue #730 
Proposition de PR (la doc sera complétée avant validation) : 
- par défaut si coordinates = "true" on affiche les degré décimaux
- si certains désirent les coordonnées en degrés minutes secondes , ajout d'une option coordinatestype="dms"
J'ai fait le choix de passer par défaut en décimaux qui semble le besoin des utilisateurs et de permettre à ceux qui veulent du dms de l'avoir avec une option en plus.
> Option coordinates en degré décimaux

- demo/addons/filter/js/filter.js
Cette PR corrige l'issue #845 en remplaçant l'opérateur CQL "=" par "LIKE" afin d'avoir un export des données dont la valeur contient le filtre.
Attention, cette PR ne permet pas d'avoir uniquement les features dont la valeur est strictement égale.
Il faudrait une évolution pour renseigner l'opérateur qui doit être appliqué dans le cas d'un champ avec séparateur type : 
`{"public": "jeunes,adultes,enfants"}`
> [Filter] #845 - download et dataSeparator

- pages/error_400.html
- pages/error_404.html
Permet d'ajouter 2 boutons pour voir le XML ou le recharger.
Cela évite de devoir ressaisir le XML quand on tombe sur la page d'erreur et on conserve cette belle page.
> Page erreur - voir le xml ou recharger

- Dockerfile
- README.md
- docs/doc_tech/deploy.rst
The benefit is having a rootless docker image because we don't need to run mviewer docker image with the root user.
Also, it allows in docker the ability to force mviewer running under another user ID to more easily share the permissions with mviewerstudio or any other programs.
See for more info: https://stackoverflow.com/questions/63108119/how-to-run-an-nginx-container-as-non-root
> Switch docker image to NGINX unprivileged

- .gitignore
- js/configuration.js
- js/templates.js
Bonjour,
Voici une proposition de résolution de l'issue #764 
J'ai modifié le configuration.js pour que lorsqu'il y a un "raccourci" de créé dans le mviewer via le "#", il soit maintenu lors du clic sur le titre ou sur le logo.
J'ai modifié le template.js pour que de la même manière il soit maintenu quand il existe à l'affichage/masquage d'une couche.
J'ai également modifié le gitignore pour que les xml publiés dans le dossier apps ne soient pas pris en compte. Sachant que dans les fait j'utilise un lien symbolique entre le dossier apps et mes dossier apps/application de manière à bénéficier du raccourci tout en gérant tous les fichiers de l'application dans le dossier dédié.
D'avance merci pour votre retour sur la proposition !
Bonne journée,
Pascal
> #764 masquer une couche et url courte

- css/mviewer.css
- docs/doc_tech/config_layers.rst
- js/configuration.js
- js/mviewer.js
> ref #870 
Cette PR permet de mettre en surbrillance les dates disponibles (publiées par la dimension temps) et permet de ne sélectionner que celles-ci.
Pour que ce mode de visualisation soit optionnel, un nouveau paramètre `timeshowavailable` a été ajouté.
Contenu :
> Time calendar - afficher les dates disponibles

- demo/addons/print/js/print.js
Avoid 2 map on PNG export if print extension map has been created.
> #902 #873 - clean print map to avoid 2ble map

- docs/doc_tech/config_map.rst
- js/mviewer.js
Gère une variable envoyé par mviewerstudio pour garder la cohérence entre la sélection et la prévisualisation de la carte.
> Issue-918 Fix la cohérence de zoom entre la séléction et la prévisualisation de la carte

- js/configuration.js
> ref #940 
Cette PR contient le correctif pour charger la carte si un groupe ne contient pas de couches.
> #940 Fix loading with empty group

- js/configuration.js
> red #943 
Cette PR contient un correctif pour lire un template directement écrit en String dans le XML
> #943 Read CDATA template as expected

- js/configuration.js
Cette PR corrige le problème de lecture du paramètre nohighlight actuellement présent depuis la version 3.9 (depuis le sensorthings).
> fix nohighlight param - #959

- docs/doc_tech/deploy.rst
Bonjour,
Petite erreur dans la documentation, les ports sont inversés.
Du moins à l'intérieur du container officiel, c'est bien le port 80 qui fonctionne et non le 8080.
J'ai inversé afin de ne pas utiliser le port 80 en externe. Entrée via port 8080 redirigé vers container interne port 80
C'est comme vous voulez.
Contrairement à la #982, je suis bien parti de la branche develop :wink:
> Fix Docker port mapping in deployment documentation

- demo/addons/print/js/print.js
- demo/addons/print/print.html
Cette contribution contient un correctif pour l'addon print :
- Ajout d'un ID sur le bouton de fermeture de la modal
- Au clique sur le bouton, gérer la suppression des cartes pour conserver le correctif de #902
> Fix #983 print addon

- js/info.js
- js/mviewer.js
[Issue-994 ](https://github.com/mviewer/mviewer/issues/994)
Fix les conditions pour la surbrillance des entités séléctionnées.
mviewer.js : highlightSubFeature() -> enlève la seconde condition qui bloque la condition ([issue-995](https://github.com/mviewer/mviewer/issues/995) en cours pour rétablir une condition fonctionnelle) 
info.js l.653 : Corrige la seconde condition suite à modification.
> Mise en surbrillance des entités sélectionnées (Issue-994)

- js/info.js
- js/mviewer.js
> Reprise de la PR #996 vers develop et non master
> ref issue https://github.com/mviewer/mviewer/issues/994
Corrige les conditions pour la surbrillance des entités sélectionnées.
mviewer.js : highlightSubFeature() -> enlève la seconde condition qui bloque la condition (https://github.com/mviewer/mviewer/issues/995 en cours pour rétablir une condition fonctionnelle)
info.js l.653 : Corrige la seconde condition suite à modification.
> #994 - Fix highlight selected features

- docs/doc_tech/config_app.rst
- js/measure.js
> Ref #909 
Cette PR permet de fermer l'outil de mesure avec la touche échappe, si l'outil est ouvert et les boutons visibles.
@lecault peux-tu tester que ce comportement est bien celui que tu souhaites ?
> #909 - Fermer l'outil de mesure avec la touche échappe

- js/search.js
> ref #1131
Petit correctif pour vider la recherche à chaque saisie, ou quand la recherche est vidée.
Cas que ce correctif couvrent : 
1. saisir "Rennes" dans le champ de saisie de recherche 
2. Voir que la liste affiche des résultats
3. Vider le texte saisie
4. Voir que la liste affiche toujours les résultats précédents --> KO !
5. Saisir "Brest"
6. Voir que la liste affiche la saisie précédente de "Rennes" et les nouveaux résultats pour Brest
> fix #1131 - clear search on each keydown timeout

- demo/els.xml
- docs/doc_tech/config_search.rst
- js/search.js
Cette PR contient les modifications suivantes : 
- Utilisation de la méthode `mviewer.animateToFeature` pour la recherche ELS 
- Prise en compte du paramètre `querymaponclick` pour la recherche ELS (interrogation de l'entité sélectionnée seulement si `true`)
- Création d'un nouveau paramètre `searchmaxzoomlevel` dans `searchparameters` pour gérer le niveau de zoom d'une recherche ELS ou FUSE. La valeur par défaut est 15 si non renseigné #447
- Mise à jour de la documentation avec le nouveau paramètre 
- Mise à jour de la demo `els.xml` avec un `searchmaxzoomlevel="12"`
> Mise à jour de la recherche ELS et création d'un paramètre pour la gestion du niveau de zoom FUSE/ELS

- js/info.js
Cette PR contient une modification du coeur lors de l'interrogation d'une layer (custom layer) WMS.
Le type ASYNC permet de pouvoir appeler des données supplémentaires dans le handle (ou pas) selon le besoin afin de manipuler les données à afficher dans le template lors de l'interrogation.
> #1146-use handle and async to wait potentials handle fetch

- demo/addons/fileimport/README.md
- demo/addons/fileimport/fileimport.js
- demo/csv.xml
- js/configuration.js
- js/mviewer.js
> ref #1010
Cette PR permet de couvrir plusieurs cas :
1. Avoir un champ qui permet de saisir une URL de fichier à lire
2. Pouvoir ajouter dans l'URL de la carte mviewer 3 paramètres (file, xfield, yfield) pour charger un csv à la volée (nécessite que fileimport soit actif dans la config XML de la carte). La couche sera créée à la volée et n'aura pas besoin d'être définie dans le XML.
3. Pouvoir voir dans Grist un mviewer qui affiche les données du tableau (_attention : les filtres ne s'appliquent pas automatiquement et nécessitent de mettre à jour le lien du CSV lu par mviewer_)
**Todo avant suppression du statut DRAFT :** 
**Tests possibles :** 
- https://grist.numerique.gouv.fr/o/docs/1HG28XWE7Ypy/Test-geocodage/p/2
- [Cette branche] - …
> Lire un CSV via son URL #1010
