mviewer/mviewer

README.md
=> Add white spaces for readability

css/themes/alizarin.css, css/themes/amethyst.css, css/themes/black.css, css/themes/blue.css, css/themes/carrot.css, css/themes/chambray.css, css/themes/default.css, css/themes/green.css, css/themes/green_sea.css, css/themes/nephritis.css, css/themes/peter_river.css, css/themes/pink.css, css/themes/ripe_lemon.css, css/themes/wet_asphalt.css
As suggested in #42, this PR aims to update all .css files in order to replace the height parameter in the help panel.
Now, instead of a fixed height (880px), the height is automatically adapted to the text content.
=> Update css files with auto parameter for help panel

config.xml, css/mviewer.css, index.html
This could fix #75  and harmonize buttons toolbar style with only one rule.
=> Group vertical toolbox buttons style

css/mviewer.css, css/scss/theme.scss, css/themes/alizarin.css, css/themes/amethyst.css, css/themes/black.css, css/themes/blue.css, css/themes/carrot.css, css/themes/chambray.css, css/themes/default.css, css/themes/green.css, css/themes/green_sea.css, css/themes/nephritis.css, css/themes/peter_river.css, css/themes/pink.css, css/themes/ripe_lemon.css, css/themes/wet_asphalt.css, index.html, js/mviewer.js, js/search.js
=> Responsive style update

README.md, css/mviewer.css, demo/csv.xml, demo/demo.csv, demo/index.html, index.html, js/configuration.js, js/csv.js, js/mviewer.js, js/search.js
=> Chargement dynamique d'un fichier de type csv avec une information de localisation

README.md, index.html, js/configuration.js, js/info.js, js/mviewer.js, js/templates.js
=> Authentifier les appels à des services WMS tiers protegés

js/configuration.js
=> Add version information in startup logs

js/configuration.js
=> Prepare new version

js/templates.js
Corrige l'affichage du nom de couche trop long en lien avec l'issue #173.
=> Nom de thématique trop long

README.md, demo/animate.xml, demo/demo_animate_help.html, demo/index.html, js/mviewer.js
- Ajout des paramètres `animate ` et `duration `
- Modification du README.md
- Je propose une modification de la doc en parallèle.
=> Ajout des paramètres "animate" et "duration"

js/mviewer.js
=> This fix #214 - remove space

demo/csv.xml
Replace broken link by Mviewer GitHub file for example file.
=> CSV Demo - replace broken link

.github/workflows/docker-build.yaml
Fixes #245
Tests: tested in a temporary github repository
=> gh actions - map master branch to docker 'latest' tag (#245)

css/mviewer.css, templates/global.lycee.mst
=> Display full bottom template correctly

js/search.js
=> Fix error data list and layer visiblity

index.html, lib/moment/moment.js
PR for issue #309 - Add moment.js lib.
=> Add moment.js to manipulate date easily

docs/doc_tech/config_fuse.rst
fix #307 
fix #305 - legendmini param already exists.
http://localhost/mviewerdoc/doc_tech/config_topics.html?highlight=mini
=> Add doc for param fusesearchthreshold

js/mviewer.js
=> Improve legendmini param

js/info.js
Fix #263 
Needs tests and reviewers.
Thanks.
=> Take tooltip params into account and improve code

README.md
=> Change kartenn link to demo

js/configuration.js
Fix and Close #347.
Source : 
https://openlayers.org/en/latest/examples/export-map.html
=> Fix Export PNG

.github/workflows/docker-build.yaml
This PR builds on master, develop and published tag. Master branch use a `stable` tag. Develop branch use `latest`.
This yaml file may not work, but I have not way to test it without commiting it :-/
=> Build on master and develop

js/custom.js
Fix type and really close #367
=> Fix simple css addon import to be really compliant with old versions

docs/doc_tech/config_map.rst, js/mviewer.js
=> Adds maxextent param to limit map extent

css/mviewer.css, index.html, js/configuration.js, mviewer.i18n.json
- Login button is now in nav bar
- icon & title button reflects connexion status (login/logout)
- user name is showned
=> Update login/logout IHM with georchestra CAS. Linked to #343

docs/doc_tech/config_map.rst
... to address https://github.com/geobretagne/mviewerstudio/pull/88#pullrequestreview-496278849
=> Adds studio label to maxextent in doc

js/info.js
=> Fix marker and Fuse, Ban search result

index.html
Update error messages with  malformed config files.
=> Update error messages #393

customcontrols/profile.js, demo/geobretagne.xml, demo/include.xml, demo/index.html, demo/lang.xml, demo/lycee_resultat_bac.mst, demo/sld.xml
Clean & update demo page before 3.4 release
=> Clean demo

.github/workflows/docker-build.yaml
=> Fix github actions version variables

js/info.js
=> Fix interrogation couche filtrée utilisant un template

demo/addons/filter/config.json, demo/addons/filter/css/filter.css, demo/addons/filter/filter.html, demo/addons/filter/js/filter.js, demo/filter/customlayers/communes.js, demo/filter/filter.xml
**Description détaillée / Describe**
Mise à jour du plugin filter : 
* Utilisation d'une seule config pour plusieurs Mviewer
* Possibilité de modifier le style de l'interface
* Possibilité de changer le titre et le texte si plusieurs layers
* Vider les tags  à la réinitialisation de tous les filtres
* Ajout d'une couche commune (customlayer) et filtre sur cette couche
#420
=> Update filter plugin

js/info.js
=> Fix marker and don't display marker for each map click event

js/info.js
=> Hide overlay if mouse over evt return no feature

js/info.js
=> Issue 428 - Bug affichage fiche d'info si aucune géométrie retournée

docs/doc_tech/config_map.rst
Modification de l'astuce dans page configurer option de la carte
=> Doc config pin issue 316

demo/fuse.xml, docs/doc_tech/config_search.rst, js/info.js, js/mviewer.js, js/search.js
=> Allow to hide banmarker and show others marker

js/info.js
`serialized` property is added to template input feature before the rendering.
eg.
```js
{
name: 'Paris',
code:  75000,
dep: 75
}
```
Somehow, this property (which was initially a key/value pairs object containing all features properties) became a full GeoJSON object, including the geometry.
This PR aims to fix it, and refactor a bit the creation of both  `serialized` and `fields_kv` bbjects.
=> Fix serialized property in mustache templating

demo/index.html, demo/selectionstyles.xml, docs/doc_tech/config_layers.rst, docs/doc_tech/config_styles.rst, docs/index.rst, js/featurestyles.js, js/mviewer.js
Lié à la demande #451
- Configuration des styles via config.xml
- Création de la documentation
- Création d'une configuration démo
=> Configuration des styles utilisés pour la mise en surbrillance des entités sélectionnées

js/info.js
=> Fix - Affichage du nom de la première couche comme du titre du template

js/configuration.js, js/mviewer.js
=> Correct permalink link operator

js/configuration.js, js/mviewer.js
=> merge Realease 3.6

demo/addons/layerfilter/README.md, demo/addons/layerfilter/config.json, demo/addons/layerfilter/layerfilter.js
#470
Utilisation de Fuse pour filtrer les éléments de la TOC.
une options `fuseOptions` a été rajouté pour permettre la personnalisation de la recherche fuse :
https://fusejs.io/api/options.html
=> Addon - Filtre de couche avec Fuse

js/search.js
=> Correction erreur recherche adresse IGN

css/mviewer.css
=> Corrige le décalage de l'icône du choix de couche d'item / couche

js/info.js
@lecault est-ce que tu peux tester ce correctif et voir si tu reproduis ton issue ?
Merci
=> #526 fix search result and layer filter

js/mviewer.js
=> fix tooltip on layer remove or add event

js/mviewer.js
Permet d'afficher la bonne légende et de rafraîchir directement la couche après l'ouverture d'un permalien pour avoir le bon style par défaut.
Voir #528 pour plus d'infos.
=> #528 permalien : refresh et légende

css/mviewer.css, js/mviewer.js
2 choses : 
- Suppression de la grille de fond par défaut #583 
- Ajout de la mention Afficher la légende dans les modes u et s #527
=> #527 Fix transparence grid layer et legend mviewer

demo/filter/customlayers/occurence_public_filter.js, demo/filter/filter_download.xml, demo/index.html
Mise au propre de la démo associé à la PR #605 
Pour tester en local : http://localhost/mviewer/?config=demo/filter/filter_download.xml
=> Mise au propre demo #605

demo/addons/filter/js/filter.js, demo/addons/filter/readme.md
Testé ces derniers mois sur mviewer ARS / SESAN. Merci pour la contrib.
#652
=> Plus d'options de style pour le plufin filtre

js/info.js
Exposition des features interrogées : issue #635
=> Exposition des features interrogées

docs/doc_tech/config_app.rst, js/info.js, js/templates.js
Nouveau template 'allintabs' Issue #633
=> Issue #633 / Template allintabs utilisé à Rennes Métropole

index.html
=> #661 Use same tab to go home

js/info.js
Déclenchement d'un événement lorsque le panneau d'information est prêt. Issue #637
=> Evénément sur panneau info pret

js/configuration.js
Code pour l'issue #639 qui permet d'appliquer automatiquement toutes les propriétés d'une balise layer dans l'objet couche du mviewer
=> Récupération automatique des propriétés des balises layer

demo/addons/isochroneAddon/config.json, demo/addons/isochroneAddon/isochroneAddon.html, demo/addons/isochroneAddon/isochroneAddon.js
Correction du service IGN d'isochrone.
#625
Pour tester : https://kartenn.region-bretagne.fr/kartoviz-dev/?config=demo/isochroneAddon.xml
J'ai juste un soucis qui était aussi dans la version précédente : le pointeur disparaît au bout d'une seconde.
=> correction service isochrone ign

css/mviewer.css
=> Retour à la ligne résumé métadonnée

.gitignore, README.md, package-lock.json, package.json
Permet d'utiliser Node et codesandbox par défaut sans avoir à créer le **package.json**.
(#591)
=> #677 serve mviewer with nodejs

demo/addons/filter/js/filter.js
Cette PR évite que l'application d'un filtre ne reset la position du filtre.
=> avoid position reset on select filter #699

demo/catalogue/data.json, demo/mviewer_templates/config.xml
Ajout de l'application mviewer templates dans le catalogue des démos #704 : 
& Affichage d'une couche par défaut dans la démo
=> Ajout de l'application mviewer templates dans le catalogue des démos

demo/addons/filter/css/filter.css, demo/addons/filter/js/filter.js, index.html, js/configuration.js
Corrige le chargement trop tôt des extensions type component à la fin du chargement de la config.
voir #703
=> Correction filtre et init addons

js/ogcutils.js
=> #718 garde les valeurs contenant le caractère de séparation

js/addlayers.js
> ref issue #744 
> Contribution ARS / GIP SESAN Ile-de-France - merci à eux.
Cette PR permet d'ajouter un filtre dans les paramètre d'une couche qu'on ajoute via l'URL.
Plus de détail dans l'issue #744.
=> #744 - Allow to filter layer added from URL api

docs/doc_contrib/contrib.rst, docs/doc_contrib/doc.rst, docs/doc_contrib/git.rst, docs/doc_contrib/issue.rst, docs/doc_contrib/release.rst, docs/doc_dev/custom.rst, docs/doc_dev/customcomponent.rst, docs/doc_dev/customcontrol.rst, docs/doc_dev/customcontrol_dev.rst, docs/doc_dev/customlayer.rst, docs/doc_dev/customlayer_template.rst, docs/doc_dev/dev_intro.rst, docs/doc_dev/public_fonctions.rst, docs/doc_tech/config_baselayers.rst, docs/doc_tech/config_customlayer.rst, docs/doc_tech/config_debug.rst, docs/doc_tech/config_els.rst, docs/doc_tech/config_environmentvar.rst, docs/doc_tech/config_extensions.rst, docs/doc_tech/config_fuse.rst, docs/doc_tech/config_intro.rst, docs/doc_tech/config_practices.rst, docs/doc_tech/config_search.rst, docs/doc_tech/config_topics.rst, docs/doc_tech/config_tpl.rst, docs/doc_tech/config_translate.rst, docs/doc_user/interface.rst, docs/doc_user/maps.rst, docs/index.rst
=> #778 - Typo dans la documentation

index.html, js/search.js
Fix a bad behavior in search results display.
See https://github.com/mviewer/mviewer/issues/763 & https://github.com/mviewer/mviewer/issues/762
=> Fix search i18n

docs/requirements.txt, js/configuration.js
Correction de la compilation de la doc
=> Version 3.9.3.1

js/mviewer.js
Modification du placement des tooltips mviewer de `left` à `auto`
=> Position des tooltips à "auto" #846

index.html
Pas de changement visible, testé avec les démos suivantes : 
- https://kartenn.region-bretagne.fr/kartoviz/
- https://kartenn.region-bretagne.fr/kartoviz/?config=demo/animate.xml
- https://kartenn.region-bretagne.fr/kartoviz/?config=demo/fuse.xml
- https://kartenn.region-bretagne.fr/kartoviz/?config=demo/els.xml
=> Delete searchresults to wrapper #842

apps/default.xml, demo/ign.xml, docs/doc_tech/config_search.rst, js/search.js
> ref #838
Cette PR: 
- ajoute un nouveau service type IGN pour la recherche d'adresse
- permet de limiter le nombre de requête lors de l'écriture d'une adresse (via un timeout sur l'événement clavier)
- revue du code de la recherche & refactorisation
- remplace les requêtes Ajax via Jquery par une fonction asynchrone et sans promise (via await)
=> [search] - #838 - Ajout service de recherche IGN 

index.html
Correction de ma première PR et afin de résoudre #842: 
- Suppression du `#searchresult` de la `#navbar` plutôt que du `#wrapper`
Cela est maintenant fonctionnel pour tous les modes
=> Delete #searchresult to navbar #842

docs/requirements.txt
=> Changement de la version de sphinx requise

apps/sensor.xml, css/mviewer.css, demo/sensor.xml, demo/sensorGeosas.mst, demo/sensorLora.mst, docs/doc_tech/config_layers.rst, index.html, js/configuration.js, js/featurestyles.js, js/info.js, js/mviewer.js, js/sensorFeature.js, js/sensorthings.js, js/templates.js, mviewer.i18n.json
> contribution de l'INRAE - Agrocampus via JDev
> Issue #627 
Cette première contribution permet d'intégrer la notion de sensorthings relativement à l'OGC : 
https://www.ogc.org/standards/sensorthings
Cette contribution permet d'utiliser des couches type "sensorthings".
La configuration possibles est la suivante : 
```
<layer
id="lora"
type="sensorthings"
name="API Lora"
visible="true"
legendurl="false"
queryable="true"
url="https://api.geosas.fr/lora/v1.0"
infopanel="bottom-panel"
style="sensorPoint"
top="200"
defaultSensor="ETP"
selector="id,description"
datastreamsfilter="name,id"
multidatastreamsfilter="name,description,id,unitOfMeasurements">
<template url="demo/sensorLora.mst"></template>
</layer>
```
Le parcours utilisateur est le suivant : 
1. Clic sur une entité géographique …
=> #627 - Nouvelle couche de type Sensorthings

js/mviewer.js
Modification de l'URL génératrice du QR code
=> change qr url

README.md
Cette PR devrait cibler develop et non master.
Un revert sur master est à réaliser (Reverts mviewer/mviewer#893)
...Puis refaire la PR vers develop selon le flux habituel :)
=> Pull request vers develop et non master

docs/doc_tech/config_tools.rst
Correction d'erreur de placement de balise
=> Modification de la documentation 'config_tools.rst'

docs/doc_tech/config_els.rst, js/search.js
Documentation updated
Work still in progress
=> Add multiple elasticsearch for version > 7

demo/catalogue/data.json, demo/superset.mst, demo/superset.xml
Ajout des démos suivantes :
- trackview
- draw
- superset
=> Mise à jour de la page de démo

js/draw.js, js/measure.js
Link #931
Change field and function scope
=> Correction measure tools panel 

demo/cadastre.xml, docs/doc_tech/config_urlparams.rst, js/urlParams/geoApiGouv.js, js/urlParams/ogcApiFeature.js, js/urlParams/urlParams.js, js/urlParams/utils.js
> ref #937
Permet de zoomer sur l'extent de feature récupérées via des paramètres OGC API Feature renseignés dans l'URL de la carte mviewer.
=> #937 - zoom au démarrage sur des features via ogc api

js/mviewer.js
=> mviewer alert - set timeout
